export const GENERIC_ERROR = "Something went wrong.";
export const NETWORK_ERROR = "Network issue.";
export const AUTH_ERROR = "Unauthorized access.";
export const CHALLANGE_SAME_OPTION_ERROR = "Same options are not allowed.";
export const CHALLANGE_NO_ANSWER_ERROR = "Please select question answer.";
export const FORM_ERROR = "Required fileds can't be empty.";
export const CHALLANGE_CREATE_ERROR = "Please follow all the rules before creating a challenge.";
export const CHALLANGE_NO_OPTION_ERROR= "Please fill up all options fields.";
export const CHALlENGE_QUIZZES_GENERATE_ERROR= "Some fields are Required. please fill up";
export const CHALLANGE_QUIZ_LIMIT_ERROR= "You have reached quizzes limit.";
export const CHALLANGE_NOT_FOUND_ERROR= "Challange can't be found.";
export const USER_NOT_FOUND_ERROR= "User can't be found.";
export const CHALLANGE_BACKEND_CREATE_ERROR= "Challange can't be created. please try again.";
export const CHALLANGE_GENERIC_ERROR= "Something went wrong. please make sure no any empty fields and non selected option";
export const QUESTION_GET_ERROR= "No any questions left.";
export const RESULT_REQUEST_ERROR= "Please complete the challenge to see the result";
export const CHALLENGE_ACCESS_ERROR= "Challenge not found or you don't have access to this challenge.";
export const ALL_FIELDS_REQUIRED_ERROR= "All fields are required. Please fill them all in.";
export const ROOM_CANT_FOUND_ERROR= "Something went wrong. Room can't be found.";
export const ROOM_NOT_ALLOWED_ERROR= "User is not allowed to delete this room.";
export const ROOM_PLAYERS_LIMIT_ERROR= "Player limit has to be even, and it can’t be less than 2 or more than 6.";
export const ROOM_QUESTIONS_LENGTH_ERROR= "Questions must be more than 2 and less or equal to 25.";
export const ROOM_NOT_ALLOWED_JOIN_ERROR= "User is not allowed to join this room.";
export const ROOM_REACHED_LIMIT_ERROR= "Room reached players limit.";
export const ROOM_ALREADY_EXIST_ERROR= "Room can't be created. You already have a hosted room.";
export const ROOM_ALREADY_IN_ROOM_ERROR= "Please leave your current room before joining/creating another one.";
export const ROOM_JOIN_SAME_ERROR= "You're already in this room.";
// export const _ERROR= "";
// export const _ERROR= "";
// export const _ERROR= "";
// export const _ERROR= "";
// export const _ERROR= "";
// export const _ERROR= "";
// export const _ERROR= "";
// export const _ERROR= "";
// export const _ERROR= "";
// export const _ERROR= "";
export const CHALLENGE_SUCCESS= "Challenge created successfully.";
export const CHALLENGE_DELETE_SUCCESS= "Challenge deleted successfully.";
export const ATTEMPT_DELETE_SUCCESS= "Attempt deleted successfully.";
export const CHALLENGE_UPDATE_SUCCESS= "Challenge updated successfully."
export const USER_UPDATE_SUCCESS= "User updated successfully."
export const ROOM_JOIN_SUCCESS = "User joined in room successfully.";
export const PLAYER_KICK_SUCCESS = "Player has been kicked from room successfully.";
// export const _SUCCESS = "";
// export const _SUCCESS = "";
// export const _SUCCESS = "";
// export const _SUCCESS = "";
// export const _SUCCESS = "";
// export const _SUCCESS = "";
// export const _SUCCESS = "";
// export const _SUCCESS = "";
// export const _SUCCESS = "";
// export const _SUCCESS = "";
// export const _SUCCESS = "";
// export const _SUCCESS = "";
// export const _SUCCESS = "";
// export const _SUCCESS = "";




export const ATEMPT_ALREADY_EXIST_WARNING= "Since you’ve already begun this challenge, certain questions may have responses available.";
// export const _WARNING= "";
// export const _WARNING= "";
// export const _WARNING= "";
// export const _WARNING= "";